### ISSUE TITLE
Standardjs 和 Prettier  区别在哪里···功能方面或者易用性方面

### ISSUE THREAD

**Issue by DeckardCainCN** [ykfe/fe-dev-playbook#31]
Standardjs 和 Prettier 区别在哪里···功能方面或者易用性方面

**Comment by qiurenbo** [comment]
Standardjs 和 Prettier 区别在哪里···功能方面或者易用性方面

**Comment by zhangyuang** [comment]
与eslint不同两者的目的都是强制约束你的代码风格。
但是prettier可以通过自己再定义一个rc文件来修改他的默认的配置，standardjs不可以，且强烈不推荐你尝试这样做。
易用性方面，两种都提供了相关的cli以及vscode插件可以保存自动格式化代码或者用cli来格式化。
但是standard明显更简单0配置，看官网包含的内容就知道了。prettier在大部分情况下还要结合eslint一起使用。
个人体验：如果你是不喜欢写分号党，建议使用[standard](https://standardjs.com/readme-zhcn.html)。(注：不写分号在99.99%的情况下不会对你的代码造成影响。要深入了解可以看[这篇回答](https://www.zhihu.com/question/20298345/answer/49551142)
 总结：我个人还是强推standard，因为prettier每个项目的配置可能都不一样，完全失去了我想统一代码风格的初衷

**Comment by DeckardCainCN** [comment]
:smile: 这个设计哲学有点意思··· 感谢您的耐心回复~ :+1: 。但是我发现···在 VSCode 上相关插件有点悲剧，自动格式化无法运行（文件保存的时候），这 Issue 还开着... [ autoFixOnSave not working! #83](https://github.com/standard/vscode-standardjs/issues?utf8=%E2%9C%93&q=save)

**Comment by zhangyuang** [comment]
> 😄 这个设计哲学有点意思··· 感谢您的耐心回复~ 👍 。但是我发现···在 VSCode 上相关插件有点悲剧，自动格式化无法运行（文件保存的时候），这 Issue 还开着... [ autoFixOnSave not working! #83](https://github.com/standard/vscode-standardjs/issues?utf8=%E2%9C%93&q=save)

我这边是可以的，前提是你全局装了standard或者当前项目装了standard才可以生效。并且vscode需要安装standardjs插件，然后在vscode的配置文件中加入以下设置。可以参考[egg-react-ssr](https://github.com/ykfe/egg-react-ssr)这个项目的配置，ts的话用tslint-config-standard
```
 "standard.autoFixOnSave": true,
```
给你录了一个gif
![image](http://ykfe.net/assets/img/standard.bf451119.gif)

**Comment by zhangyuang** [comment]
blob:https://www.shipinyasuo.com/0dbea9d2-2c12-4708-b57f-b856c0df02b8

**Comment by DeckardCainCN** [comment]
经过多次尝试终于成功~ 谢谢 ~ :smile: 。不过我还是使用了 semistandard 的版本

**Comment by chenbingchang** [comment]
感觉我太傻了，用了eslint+prettier，然后还想加个standard
