### ISSUE TITLE
fe-dev-playbook主页、介绍页、GitHub主页的钉钉群二维码过期

### ISSUE THREAD

**Issue by yuesong-feng** [ykfe/fe-dev-playbook#48]
fe-dev-playbook主页、介绍页、GitHub主页的钉钉群二维码过期
原群为egg-react-ssr答疑群，猜测已经更改为了ssr答疑群，钉钉扫描显示二维码过期。

**Comment by zhangyuang** [comment]
https://res.wx.qq.com/op_res/rrhdxU0o2yUdgTjwgkAgO-CSFV-lArvMYzWzxl2SuvnKkcWECv7SXswEYjk2pPcDcL43r0kz_MIp_fsxPPqQ2Q

你可以提个pr来更新

**Comment by yuesong-feng** [comment]
已更新三处二维码。
