### ISSUE TITLE
Independent request

### ISSUE THREAD

**Issue by lvfangren** [ykfe/fe-dev-playbook#56]
hello， Based on this warehouse, I fork a copy to my account.

Based on the current situation, I will modify some content and organize it into my own.

1: Because there may be more revisions (mainly new additions), so I can't pr
2: A lot of the original content will be retained, so I fork

If you refuse such behavior, you can notify me. Thanks a lot

**Comment by zhangyuang** [comment]
The original idea of doc is not big and complete documemt but tiny and pretty, i don't want to add more complicated text only less text by pr

**Comment by lvfangren** [comment]
However, I want to produce a complete doc based on this 😂
